app:
  # app run port
  port: 8000
  pprof_port: 8090
  app_env: "local"
  app_debug: true
  app_name: "news"
  graceful_wait: 5s

# db config
db:
  user: ""
  password: ""
  host: ""
  port: ""
  dbname: ""
